nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/Inventory$ ls
asgi.py  __init__.py  __pycache__  settings.py  settings.py~  urls.py  wsgi.py
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/Inventory$ cd ..
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ rm -f users
rm: cannot remove 'users': Is a directory
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ rm -r users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py startapp Users
Traceback (most recent call last):
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 158, in get_app_config
    return self.app_configs[app_label]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 283, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 208, in get_model
    app_config = self.get_app_config(app_label)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 165, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'users'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 22, in <module>
    main()
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/admin/__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/forms.py", line 20, in <module>
    UserModel = get_user_model()
                ^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 289, in get_user_model
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.CustomUser' that has not been installed
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py startapp user
Traceback (most recent call last):
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 158, in get_app_config
    return self.app_configs[app_label]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 283, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 208, in get_model
    app_config = self.get_app_config(app_label)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 165, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'users'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 22, in <module>
    main()
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/admin/__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/forms.py", line 20, in <module>
    UserModel = get_user_model()
                ^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 289, in get_user_model
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.CustomUser' that has not been installed
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py startapp users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ cd users/
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ ls
admin.py  apps.py  __init__.py  migrations  models.py  tests.py  views.py
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$cd ..
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations
No changes detected
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, product, sessions
Running migrations:
  Applying product.0006_product_date_added_product_last_updated... OK
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations users
No installed app with label 'users'.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations users
No changes detected in app 'users'
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, product, sessions
Running migrations:
  No migrations to apply.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ cd users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ ls
admin.py  apps.py  __init__.py  migrations  models.py  __pycache__  tests.py  views.py
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ git branch
WARNING: terminal is not fully functional
Press RETURN to continue 

  forms
  main
* users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ ls
admin.py  apps.py  __init__.py  migrations  models.py  models.py~  __pycache__  tests.py  views.py
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ cd ..
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations users
Traceback (most recent call last):
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 22, in <module>
    main()
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users/models.py", line 2, in <module>
    from djang.contrib.auth.models import AbstractUser
ModuleNotFoundError: No module named 'djang'
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations users
Traceback (most recent call last):
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 22, in <module>
    main()
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users/models.py", line 2, in <module>
    from djang.contrib.auth.models import AbstractUser
ModuleNotFoundError: No module named 'djang'
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations users
Migrations for 'users':
  users/migrations/0001_initial.py
    + Create model CustomUser
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py migrate
Traceback (most recent call last):
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 22, in <module>
    main()
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 117, in handle
    executor.loader.check_consistent_history(connection)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ cd ..
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone$ ls
Inventory
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone$ cd ..
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab$ ls
advanced  advanced-api-project  advanced_features_and_security  api_project  capstone  django_blog  django-models  Introduction_to_Django  rlae  social_media_api
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab$ django-admin startapp inventory
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab$ cd Introduction_to_Django/
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/Introduction_to_Django$ ls
LibraryProject
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/Introduction_to_Django$ cd ..
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab$ ls
advanced  advanced-api-project  advanced_features_and_security  api_project  capstone  django_blog  django-models  Introduction_to_Django  inventory  rlae  social_media_api
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab$ ls
advanced  advanced-api-project  advanced_features_and_security  api_project  capstone  django_blog  django-models  Introduction_to_Django  inventory  rlae  social_media_api
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab$ cd capstone/
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone$ ls
Inventory
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone$ cd Inventory/
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations
Traceback (most recent call last):
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 22, in <module>
    main()
  File "/home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/core/management/commands/makemigrations.py", line 159, in handle
    loader.check_consistent_history(connection)
  File "/home/nii-okai/myenv~/lib/python3.12/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py dbshell
SQLite version 3.45.1 2024-01-30 16:01:20
Enter ".help" for usage hints.
sqlite> SELECT user, name FROM django_migrations ORDER BY applied;
Parse error: no such column: user
  SELECT user, name FROM django_migrations ORDER BY applied;
         ^--- error here
sqlite> SELECT users, name FROM django_migrations ORDER BY applied;
Parse error: no such column: users
  SELECT users, name FROM django_migrations ORDER BY applied;
         ^--- error here
sqlite> SELECT 'users', name FROM django_migrations ORDER BY applied;
users|0001_initial
users|0001_initial
users|0001_initial
users|0002_logentry_remove_auto_add
users|0003_logentry_add_action_flag_choices
users|0002_remove_content_type_name
users|0002_alter_permission_name_max_length
users|0003_alter_user_email_max_length
users|0004_alter_user_username_opts
users|0005_alter_user_last_login_null
users|0006_require_contenttypes_0002
users|0007_alter_validators_add_error_messages
users|0008_alter_user_username_max_length
users|0009_alter_user_last_name_max_length
users|0010_alter_group_name_max_length
users|0011_update_proxy_permissions
users|0012_alter_user_first_name_max_length
users|0001_initial
users|0001_initial
users|0002_warehousemanager_remove_product_warehouse_id_and_more
users|0003_warehouse_product_warehouse_id
users|0004_alter_product_warehouse_id
users|0005_product_product_description_alter_product_product_id
users|0006_product_date_added_product_last_updated
sqlite> .quit
CommandError: "sqlite3 /home/nii-okai/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/db.sqlite3" returned non-zero exit status 1.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ rm db.sqlite3
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ find . -path "*/migrations/*.py" -not -name "__init__.py" -delete


nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ find . -path "*/migrations/*.pyc" -delete



nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigration
Unknown command: 'makemigration'. Did you mean makemigrations?
Type 'manage.py help' for usage.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigration
Unknown command: 'makemigration'. Did you mean makemigrations?
Type 'manage.py help' for usage.
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py makemigrations
Migrations for 'product':
  product/migrations/0001_initial.py
    + Create model Category
    + Create model Supplier
    + Create model Warehouse
    + Create model WarehouseManager
    + Create model Product
    + Add field warehouse_manager to warehouse
Migrations for 'users':
  users/migrations/0001_initial.py
    + Create model CustomUser
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, product, sessions, users
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying users.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying product.0001_initial... OK
  Applying sessions.0001_initial... OK
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ ls
db.sqlite3  Inventory  manage.py  product  users
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory$ cd users/
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ ls
admin.py  apps.py  __init__.py  migrations  models.py  models.py~  __pycache__  tests.py  views.py
nii-okai@nii-okai-VirtualBox:~/Documents/alx/python/python_introduction/Introduction_to_Django/Alx_DjangoLearnLab/capstone/Inventory/users$ 